language: python

python:
 - "3.6"

env:
  - DJANGO=2.1.5 DB=sqlite3

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - cd src
  - coverage run --source=bookingapp manage.py test

cache: pip