language: python

python:
 - "3.4"

env:
  - DJANGO=2.1.5 DB=sqlite3

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=src/bookingapp src/manage.py test

after_success:
  coveralls